// GET ALL
GET http://localhost:5000/api/productos/

###
// CREATE
POST http://localhost:5000/api/productos
Content-Type: application/json

{
    "usuarioId": "5",
    "ordenId": "7",
    "nombre": "productoTest3",
    "precio": "2100",
    "descripcion": "Test 1 producto"
}

###
// GET BY ID
GET http://localhost:5000/api/productos/2

###
// UPDATE
PUT http://localhost:5000/api/productos/1
Content-Type: application/json

{
    "nombre": "productoTest2",
    "precio": "2000",
    "descripcion": "Test 2 producto"
}

###
// DELETE
DELETE http://localhost:5000/api/productos/1
